server:
  port: 8080
  servlet:
    contextPath: /skeleton

info:
  app:
    name: Spring project skeleton
    description: This is project contains a basic structure of spring boot project

spring:
  profiles:
    active: local
  ############# Datasource related configuration ###########
  datasource:
    url: 'jdbc:mysql://${skeleton.mysql.host}:3306/skeleton'
    username: '${skeleton.mysql.username}'
    password: '${skeleton.mysql.password}'
  liquibase:
    change-log: 'classpath:/db.changelog/changelog-master.xml'
  jpa:
    show-sql: true
